# Generated by Django 5.0.2 on 2024-02-23 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='название')),
                ('level', models.PositiveIntegerField(verbose_name='уровень звена')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='почта')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='страна')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='город')),
                ('street', models.CharField(blank=True, max_length=100, null=True, verbose_name='улица')),
                ('house', models.CharField(blank=True, max_length=10, null=True, verbose_name='№ дома')),
                ('debt', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='задолженность перед постащиком')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата и время создания')),
                ('products', models.ManyToManyField(blank=True, null=True, to='products.product', verbose_name='продукты')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traders.trader', verbose_name='поставщик')),
            ],
        ),
    ]
