# Generated by Django 5.0.2 on 2024-02-23 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('traders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader',
            name='products',
            field=models.ManyToManyField(to='products.product', verbose_name='продукты'),
        ),
        migrations.AlterField(
            model_name='trader',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='traders.trader', verbose_name='поставщик'),
        ),
    ]
