# Generated by Django 5.0.2 on 2024-02-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('traders', '0002_alter_trader_products_alter_trader_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader',
            name='debt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='задолженность перед постащиком'),
        ),
        migrations.AlterField(
            model_name='trader',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='products.product', verbose_name='продукты'),
        ),
    ]
